### ISSUE TITLE
Update links to PDF archives of Handbooks

### ISSUE THREAD

**Issue by imcbride** [middlebury/college-handbook#217]
Please update the links on this page https://www.middlebury.edu/handbook/pages/v-handbook-archive/

2007-2008: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2007_2008.pdf?fv=SrlJAH96

2008-2009: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2008_2009.pdf?fv=5qX5CVDM

2009-2010: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2009_2010.pdf?fv=r4h2unEb

2010-2011: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2010_2011.pdf?fv=ri03udQT

2012-2013: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2012_2013.pdf?fv=QG_aeHsd

2013-2014: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2013_2014.pdf?fv=AysFKVjv

2014-2015: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2014_2015.pdf?fv=8R9qHk_t

2015-2016: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2015_2016.pdf?fv=7tQsUA7_

2016-2017: https://www.middlebury.edu/office/sites/www.middlebury.edu.office/files/2022-12/collegehandbookmiddlebury2016_2017.pdf?fv=acSouxDD

And please add:

2017-2018: https://web.archive.org/web/20210115184109/http://www.middlebury.edu/about/handbook/handbook_archive/handbook-2017-2018

2018-2019: https://web.archive.org/web/20210115184109/http://www.middlebury.edu/about/handbook/handbook_archive/handbook-2018-2019

**Comment by poojagunturu96** [comment]
Issue resolved in commit [35cab0d](https://github.com/middlebury/college-handbook/commit/35cab0dea7567eb914385e095b106b978e316901).
